import { CareerData } from '@/lib/firebase/firestore';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// デザイン定義 (標準フォントを使用)
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    color: '#333',
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    borderBottom: '1.5pt solid #000',
    paddingBottom: 8,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    color: '#666',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    backgroundColor: '#f0f0f0',
    padding: 4,
    marginBottom: 8,
    borderLeft: '4pt solid #333',
  },
  item: {
    marginBottom: 4,
    flexDirection: 'row',
  },
  bullet: {
    width: 12,
  },
  content: {
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#aaa',
    borderTop: '0.5pt solid #eee',
    paddingTop: 8,
  },
});

interface ResumeDocumentProps {
  data: CareerData;
  userEmail: string;
}

export const ResumeDocument = ({ data, userEmail }: ResumeDocumentProps) => {
  // データの安全な抽出
  const skills = Array.isArray(data?.skills) ? data.skills : [];
  const experience = Array.isArray(data?.experience) ? data.experience : [];
  const strengths = Array.isArray(data?.strengths) ? data.strengths : [];
  const goals = Array.isArray(data?.goals) ? data.goals : [];
  const email = String(userEmail || "No Email");

  // react-pdf は標準で日本語フォントを持っていないため、
  // フォント登録なしでは日本語が消えるか文字化けする可能性がありますが、
  // まずは「PDFが生成されること」を最優先にし、エラーを回避します。
  return (
    <Document title="Career Document">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>RESUME / CAREER RECORD</Text>
          <Text style={styles.subtitle}>{email}</Text>
        </View>

        {skills.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>SKILLS</Text>
            {skills.map((item, i) => (
              <View key={`s-${i}`} style={styles.item}>
                <Text style={styles.bullet}>-</Text>
                <Text style={styles.content}>{String(item || "")}</Text>
              </View>
            ))}
          </View>
        )}

        {experience.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>EXPERIENCE</Text>
            {experience.map((item, i) => (
              <View key={`e-${i}`} style={styles.item}>
                <Text style={styles.bullet}>-</Text>
                <Text style={styles.content}>{String(item || "")}</Text>
              </View>
            ))}
          </View>
        )}

        {strengths.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>STRENGTHS</Text>
            {strengths.map((item, i) => (
              <View key={`st-${i}`} style={styles.item}>
                <Text style={styles.bullet}>-</Text>
                <Text style={styles.content}>{String(item || "")}</Text>
              </View>
            ))}
          </View>
        )}

        {goals.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>GOALS</Text>
            {goals.map((item, i) => (
              <View key={`g-${i}`} style={styles.item}>
                <Text style={styles.bullet}>-</Text>
                <Text style={styles.content}>{String(item || "")}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={styles.footer} fixed>
          <Text>Generated by CareerAdvisor AI - {new Date().toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  );
};
