import { CareerData } from '@/lib/firebase/firestore';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// 日本語フォントをローカルアセットから登録
Font.register({
  family: 'Noto Sans JP',
  src: 'https://cdn.jsdelivr.net/gh/shun-shun/noto-sans-jp-subset-for-pdf@master/NotoSansJP-Regular.ttf'
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Noto Sans JP',
    fontSize: 10,
    color: '#333',
    lineHeight: 1.6,
  },
  header: {
    marginBottom: 30,
    borderBottom: '2pt solid #000',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    backgroundColor: '#f5f5f5',
    padding: 6,
    marginBottom: 10,
    borderLeft: '4pt solid #333',
  },
  item: {
    marginBottom: 6,
    flexDirection: 'row',
  },
  bullet: {
    width: 15,
    textAlign: 'center',
  },
  content: {
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#999',
    borderTop: '0.5pt solid #eee',
    paddingTop: 10,
  },
});

interface ResumeDocumentProps {
  data: CareerData;
  userEmail: string;
}

export const ResumeDocument = ({ data, userEmail }: ResumeDocumentProps) => {
  const safeData = data || {};
  
  // React-pdfのクラッシュ（空文字や不正オブジェクトの描画）を防ぐための厳格なフィルタリング
  const safeStringArray = (arr: any) => {
    if (!Array.isArray(arr)) return [];
    return arr
      .map(item => typeof item === 'string' ? item.trim() : String(item || '').trim())
      .filter(item => item !== '' && item !== '[object Object]');
  };

  const skills = safeStringArray(safeData.skills);
  const experience = safeStringArray(safeData.experience);
  const strengths = safeStringArray(safeData.strengths);
  const goals = safeStringArray(safeData.goals);
  const email = userEmail || "メールアドレス未設定";

  return (
    <Document title="職務経歴書">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>職務経歴書</Text>
          <Text style={styles.subtitle}>{email}</Text>
        </View>

        {/* スキル */}
        {skills.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>テクニカルスキル・資格</Text>
            {skills.map((skill, i) => (
              <View key={`s-${i}`} style={styles.item}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.content}>{String(skill || "")}</Text>
              </View>
            ))}
          </View>
        )}

        {/* 職務経歴 */}
        {experience.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>職務経歴</Text>
            {experience.map((exp, i) => (
              <View key={`e-${i}`} style={styles.item}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.content}>{String(exp || "")}</Text>
              </View>
            ))}
          </View>
        )}

        {/* 自己PR・強み */}
        {strengths.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>自己PR / 強み</Text>
            {strengths.map((strength, i) => (
              <View key={`st-${i}`} style={styles.item}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.content}>{String(strength || "")}</Text>
              </View>
            ))}
          </View>
        )}

        {/* 目標 */}
        {goals.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>今後の展望 / キャリア目標</Text>
            {goals.map((goal, i) => (
              <View key={`g-${i}`} style={styles.item}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.content}>{String(goal || "")}</Text>
              </View>
            ))}
          </View>
        )}

        <View style={styles.footer} fixed>
          <Text>Generated by CareerAdvisor AI - {new Date().toLocaleDateString('ja-JP')}</Text>
        </View>
      </Page>
    </Document>
  );
};
